version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app_blue
      - app_green
    networks:
      - app_network
    command: nginx -g 'daemon off;'

  app_blue:
    image: ${BLUE_IMAGE}
    container_name: app_blue
    ports:
      - "8081:${PORT:-8080}"
    environment:
      - APP_POOL=blue
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT:-8080}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-8080}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  app_green:
    image: ${GREEN_IMAGE}
    container_name: app_green
    ports:
      - "8082:${PORT:-8080}"
    environment:
      - APP_POOL=green
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT:-8080}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-8080}/healthz"]
      interval: 5s
      timeout: 3s
      retries: 3

  alert_watcher:
    image: python:3.11-slim
    container_name: alert_watcher
    volumes:
      - nginx_logs:/var/log/nginx
      - ./watcher.py:/app/watcher.py
      - ./requirements.txt:/app/requirements.txt
    working_dir: /app
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - ERROR_RATE_THRESHOLD=${ERROR_RATE_THRESHOLD:-2}
      - WINDOW_SIZE=${WINDOW_SIZE:-200}
      - ALERT_COOLDOWN_SEC=${ALERT_COOLDOWN_SEC:-300}
    networks:
      - app_network
    command: sh -c "pip install -q -r requirements.txt && python watcher.py"
    depends_on:
      - nginx

networks:
  app_network:
    driver: bridge

volumes:
  nginx_logs: